//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Actos.Utiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lenguaje {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lenguaje() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Actos.Utiles.Lenguaje", typeof(Lenguaje).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aceptar.
        /// </summary>
        public static string Aceptar {
            get {
                return ResourceManager.GetString("Aceptar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activo.
        /// </summary>
        public static string Activo {
            get {
                return ResourceManager.GetString("Activo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actos.
        /// </summary>
        public static string Actos {
            get {
                return ResourceManager.GetString("Actos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agresor.
        /// </summary>
        public static string Agresor {
            get {
                return ResourceManager.GetString("Agresor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agresores.
        /// </summary>
        public static string Agresores {
            get {
                return ResourceManager.GetString("Agresores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El agresor no existe..
        /// </summary>
        public static string AgresorNoExiste {
            get {
                return ResourceManager.GetString("AgresorNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El agresor no es válido..
        /// </summary>
        public static string AgresorNoValido {
            get {
                return ResourceManager.GetString("AgresorNoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El agresor debe tener nombre y/o apellido y/o apodo..
        /// </summary>
        public static string AgresorSinNombreApellidoApodo {
            get {
                return ResourceManager.GetString("AgresorSinNombreApellidoApodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El agresor ya se encuentra eliminado..
        /// </summary>
        public static string AgresorYaEliminado {
            get {
                return ResourceManager.GetString("AgresorYaEliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altos.
        /// </summary>
        public static string Altos {
            get {
                return ResourceManager.GetString("Altos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El antecedente no existe..
        /// </summary>
        public static string AntecedenteNoExiste {
            get {
                return ResourceManager.GetString("AntecedenteNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El antecedente no es válido..
        /// </summary>
        public static string AntecedenteNoValido {
            get {
                return ResourceManager.GetString("AntecedenteNoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antecedentes.
        /// </summary>
        public static string Antecedentes {
            get {
                return ResourceManager.GetString("Antecedentes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El antecedente ya se encuentra eliminado..
        /// </summary>
        public static string AntecedenteYaEliminado {
            get {
                return ResourceManager.GetString("AntecedenteYaEliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apellido.
        /// </summary>
        public static string Apellido {
            get {
                return ResourceManager.GetString("Apellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El apellido no es válido..
        /// </summary>
        public static string ApellidoNoValido {
            get {
                return ResourceManager.GetString("ApellidoNoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aplicar cambios.
        /// </summary>
        public static string AplicarCambios {
            get {
                return ResourceManager.GetString("AplicarCambios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apodo.
        /// </summary>
        public static string Apodo {
            get {
                return ResourceManager.GetString("Apodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El apodo no es válido..
        /// </summary>
        public static string ApodoNoValido {
            get {
                return ResourceManager.GetString("ApodoNoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bajos.
        /// </summary>
        public static string Bajos {
            get {
                return ResourceManager.GetString("Bajos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calle.
        /// </summary>
        public static string Calle {
            get {
                return ResourceManager.GetString("Calle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La calle no es válida..
        /// </summary>
        public static string CalleNoValida {
            get {
                return ResourceManager.GetString("CalleNoValida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caracteristicas.
        /// </summary>
        public static string Caracteristicas {
            get {
                return ResourceManager.GetString("Caracteristicas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las caracteristicas no son válidas..
        /// </summary>
        public static string CaracteristicasNoValidas {
            get {
                return ResourceManager.GetString("CaracteristicasNoValidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clave.
        /// </summary>
        public static string Clave {
            get {
                return ResourceManager.GetString("Clave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clave actual.
        /// </summary>
        public static string ClaveActual {
            get {
                return ResourceManager.GetString("ClaveActual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La clave no es válida..
        /// </summary>
        public static string ClaveNoValida {
            get {
                return ResourceManager.GetString("ClaveNoValida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clave nueva.
        /// </summary>
        public static string ClaveNueva {
            get {
                return ResourceManager.GetString("ClaveNueva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El código de área debe ser numérico..
        /// </summary>
        public static string CodigoAreaNoNumerico {
            get {
                return ResourceManager.GetString("CodigoAreaNoNumerico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El código de área no es válido..
        /// </summary>
        public static string CodigoAreaNoValido {
            get {
                return ResourceManager.GetString("CodigoAreaNoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar clave.
        /// </summary>
        public static string ConfirmarClave {
            get {
                return ResourceManager.GetString("ConfirmarClave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Las coordenadas de ubicación no son válidas..
        /// </summary>
        public static string CoordenadasNoValidas {
            get {
                return ResourceManager.GetString("CoordenadasNoValidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departamento.
        /// </summary>
        public static string Departamento {
            get {
                return ResourceManager.GetString("Departamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El departamento no es válido..
        /// </summary>
        public static string DepartamentoNoValido {
            get {
                return ResourceManager.GetString("DepartamentoNoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direcciones.
        /// </summary>
        public static string Direcciones {
            get {
                return ResourceManager.GetString("Direcciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elegir agresor.
        /// </summary>
        public static string ElegirAgresor {
            get {
                return ResourceManager.GetString("ElegirAgresor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elegir víctima.
        /// </summary>
        public static string ElegirVictima {
            get {
                return ResourceManager.GetString("ElegirVictima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eliminar.
        /// </summary>
        public static string Eliminar {
            get {
                return ResourceManager.GetString("Eliminar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estado.
        /// </summary>
        public static string Estado {
            get {
                return ResourceManager.GetString("Estado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El estado no es válido..
        /// </summary>
        public static string EstadoNoValido {
            get {
                return ResourceManager.GetString("EstadoNoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fecha.
        /// </summary>
        public static string Fecha {
            get {
                return ResourceManager.GetString("Fecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La fecha no es válida..
        /// </summary>
        public static string FechaNoValida {
            get {
                return ResourceManager.GetString("FechaNoValida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtros.
        /// </summary>
        public static string Filtros {
            get {
                return ResourceManager.GetString("Filtros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inactivo.
        /// </summary>
        public static string Inactivo {
            get {
                return ResourceManager.GetString("Inactivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localidad.
        /// </summary>
        public static string Localidad {
            get {
                return ResourceManager.GetString("Localidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La localidad no existe..
        /// </summary>
        public static string LocalidadNoExiste {
            get {
                return ResourceManager.GetString("LocalidadNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La localidad no es válida..
        /// </summary>
        public static string LocalidadNoValida {
            get {
                return ResourceManager.GetString("LocalidadNoValida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La localidad de reemplazo no existe..
        /// </summary>
        public static string LocalidadReemplazoNoExiste {
            get {
                return ResourceManager.GetString("LocalidadReemplazoNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La localidad de reemplazo no es válida..
        /// </summary>
        public static string LocalidadReemplazoNoValida {
            get {
                return ResourceManager.GetString("LocalidadReemplazoNoValida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapa.
        /// </summary>
        public static string Mapa {
            get {
                return ResourceManager.GetString("Mapa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medios.
        /// </summary>
        public static string Medios {
            get {
                return ResourceManager.GetString("Medios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Métodos.
        /// </summary>
        public static string Metodos {
            get {
                return ResourceManager.GetString("Metodos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los métodos no son válidos..
        /// </summary>
        public static string MetodosNoValidos {
            get {
                return ResourceManager.GetString("MetodosNoValidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modificar.
        /// </summary>
        public static string Modificar {
            get {
                return ResourceManager.GetString("Modificar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nombre.
        /// </summary>
        public static string Nombre {
            get {
                return ResourceManager.GetString("Nombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El nombre no es válido..
        /// </summary>
        public static string NombreNoValido {
            get {
                return ResourceManager.GetString("NombreNoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nueva víctima.
        /// </summary>
        public static string NuevaVictima {
            get {
                return ResourceManager.GetString("NuevaVictima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo.
        /// </summary>
        public static string Nuevo {
            get {
                return ResourceManager.GetString("Nuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo agresor.
        /// </summary>
        public static string NuevoAgresor {
            get {
                return ResourceManager.GetString("NuevoAgresor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuevo antecedente.
        /// </summary>
        public static string NuevoAntecedente {
            get {
                return ResourceManager.GetString("NuevoAntecedente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número.
        /// </summary>
        public static string Numero {
            get {
                return ResourceManager.GetString("Numero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El número no es válido..
        /// </summary>
        public static string NumeroNoValido {
            get {
                return ResourceManager.GetString("NumeroNoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observaciones.
        /// </summary>
        public static string Observaciones {
            get {
                return ResourceManager.GetString("Observaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocupación.
        /// </summary>
        public static string Ocupacion {
            get {
                return ResourceManager.GetString("Ocupacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La ocupación no es válida..
        /// </summary>
        public static string OcupacionNoValida {
            get {
                return ResourceManager.GetString("OcupacionNoValida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perjuicios.
        /// </summary>
        public static string Perjuicios {
            get {
                return ResourceManager.GetString("Perjuicios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Los perjuicios no son válidos..
        /// </summary>
        public static string PerjuiciosNoValidos {
            get {
                return ResourceManager.GetString("PerjuiciosNoValidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piso.
        /// </summary>
        public static string Piso {
            get {
                return ResourceManager.GetString("Piso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El piso no es válido..
        /// </summary>
        public static string PisoNoValido {
            get {
                return ResourceManager.GetString("PisoNoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por agresor.
        /// </summary>
        public static string PorAgresor {
            get {
                return ResourceManager.GetString("PorAgresor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por apellido.
        /// </summary>
        public static string PorApellido {
            get {
                return ResourceManager.GetString("PorApellido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por apodo.
        /// </summary>
        public static string PorApodo {
            get {
                return ResourceManager.GetString("PorApodo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por nombre.
        /// </summary>
        public static string PorNombre {
            get {
                return ResourceManager.GetString("PorNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por ocupación.
        /// </summary>
        public static string PorOcupacion {
            get {
                return ResourceManager.GetString("PorOcupacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por perjuicios.
        /// </summary>
        public static string PorPerjuicios {
            get {
                return ResourceManager.GetString("PorPerjuicios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por ubicación.
        /// </summary>
        public static string PorUbicacion {
            get {
                return ResourceManager.GetString("PorUbicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Por víctima.
        /// </summary>
        public static string PorVictima {
            get {
                return ResourceManager.GetString("PorVictima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Puntajes.
        /// </summary>
        public static string Puntajes {
            get {
                return ResourceManager.GetString("Puntajes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redes sociales.
        /// </summary>
        public static string RedesSociales {
            get {
                return ResourceManager.GetString("RedesSociales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sin puntos.
        /// </summary>
        public static string SinPuntos {
            get {
                return ResourceManager.GetString("SinPuntos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Teléfonos.
        /// </summary>
        public static string Telefonos {
            get {
                return ResourceManager.GetString("Telefonos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de dirección.
        /// </summary>
        public static string TipoDireccion {
            get {
                return ResourceManager.GetString("TipoDireccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tipo de dirección no es válido..
        /// </summary>
        public static string TipoDireccionNoValido {
            get {
                return ResourceManager.GetString("TipoDireccionNoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo red social.
        /// </summary>
        public static string TipoRedSocial {
            get {
                return ResourceManager.GetString("TipoRedSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tipo de red social no es válido..
        /// </summary>
        public static string TipoRedSocialNoValido {
            get {
                return ResourceManager.GetString("TipoRedSocialNoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de teléfono.
        /// </summary>
        public static string TipoTelefono {
            get {
                return ResourceManager.GetString("TipoTelefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El tipo de teléfono no es válido..
        /// </summary>
        public static string TipoTelefonoNoValido {
            get {
                return ResourceManager.GetString("TipoTelefonoNoValido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos.
        /// </summary>
        public static string Todos {
            get {
                return ResourceManager.GetString("Todos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ubicación.
        /// </summary>
        public static string Ubicacion {
            get {
                return ResourceManager.GetString("Ubicacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La ubicación no es válida..
        /// </summary>
        public static string UbicacionNoValida {
            get {
                return ResourceManager.GetString("UbicacionNoValida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Víctima.
        /// </summary>
        public static string Victima {
            get {
                return ResourceManager.GetString("Victima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La víctima se creó con éxito..
        /// </summary>
        public static string VictimaCargada {
            get {
                return ResourceManager.GetString("VictimaCargada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La víctima no existe..
        /// </summary>
        public static string VictimaNoExiste {
            get {
                return ResourceManager.GetString("VictimaNoExiste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La víctima no es válida..
        /// </summary>
        public static string VictimaNoValida {
            get {
                return ResourceManager.GetString("VictimaNoValida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Víctimas.
        /// </summary>
        public static string Victimas {
            get {
                return ResourceManager.GetString("Victimas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La víctima ya se encuentra eliminada..
        /// </summary>
        public static string VictimaYaEliminada {
            get {
                return ResourceManager.GetString("VictimaYaEliminada", resourceCulture);
            }
        }
    }
}
