//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Actos.SitioWeb.MVC.ServicioWeb {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntidadBaseOfint", Namespace="http://schemas.datacontract.org/2004/07/Actos.Modelo.Entidades")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Actos.SitioWeb.MVC.ServicioWeb.Antecedente))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Actos.SitioWeb.MVC.ServicioWeb.Persona))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Actos.SitioWeb.MVC.ServicioWeb.Victima))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Actos.SitioWeb.MVC.ServicioWeb.Agresor))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Actos.SitioWeb.MVC.ServicioWeb.Direccion))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Actos.SitioWeb.MVC.ServicioWeb.RedSocial))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Actos.SitioWeb.MVC.ServicioWeb.Telefono))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Actos.SitioWeb.MVC.ServicioWeb.Localidad))]
    public partial class EntidadBaseOfint : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Antecedente", Namespace="http://schemas.datacontract.org/2004/07/Actos.Modelo.Entidades")]
    [System.SerializableAttribute()]
    public partial class Antecedente : Actos.SitioWeb.MVC.ServicioWeb.EntidadBaseOfint {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Actos.SitioWeb.MVC.ServicioWeb.Agresor AgresorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Actos.SitioWeb.MVC.ServicioWeb.Estado EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LatitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LongitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ObservacionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PerjuiciosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Actos.SitioWeb.MVC.ServicioWeb.Victima[] PuntajesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UbicacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Actos.SitioWeb.MVC.ServicioWeb.Victima VictimaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Actos.SitioWeb.MVC.ServicioWeb.Agresor Agresor {
            get {
                return this.AgresorField;
            }
            set {
                if ((object.ReferenceEquals(this.AgresorField, value) != true)) {
                    this.AgresorField = value;
                    this.RaisePropertyChanged("Agresor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Actos.SitioWeb.MVC.ServicioWeb.Estado Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Latitud {
            get {
                return this.LatitudField;
            }
            set {
                if ((this.LatitudField.Equals(value) != true)) {
                    this.LatitudField = value;
                    this.RaisePropertyChanged("Latitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Longitud {
            get {
                return this.LongitudField;
            }
            set {
                if ((this.LongitudField.Equals(value) != true)) {
                    this.LongitudField = value;
                    this.RaisePropertyChanged("Longitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Observaciones {
            get {
                return this.ObservacionesField;
            }
            set {
                if ((object.ReferenceEquals(this.ObservacionesField, value) != true)) {
                    this.ObservacionesField = value;
                    this.RaisePropertyChanged("Observaciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Perjuicios {
            get {
                return this.PerjuiciosField;
            }
            set {
                if ((object.ReferenceEquals(this.PerjuiciosField, value) != true)) {
                    this.PerjuiciosField = value;
                    this.RaisePropertyChanged("Perjuicios");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Actos.SitioWeb.MVC.ServicioWeb.Victima[] Puntajes {
            get {
                return this.PuntajesField;
            }
            set {
                if ((object.ReferenceEquals(this.PuntajesField, value) != true)) {
                    this.PuntajesField = value;
                    this.RaisePropertyChanged("Puntajes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ubicacion {
            get {
                return this.UbicacionField;
            }
            set {
                if ((object.ReferenceEquals(this.UbicacionField, value) != true)) {
                    this.UbicacionField = value;
                    this.RaisePropertyChanged("Ubicacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Actos.SitioWeb.MVC.ServicioWeb.Victima Victima {
            get {
                return this.VictimaField;
            }
            set {
                if ((object.ReferenceEquals(this.VictimaField, value) != true)) {
                    this.VictimaField = value;
                    this.RaisePropertyChanged("Victima");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Persona", Namespace="http://schemas.datacontract.org/2004/07/Actos.Modelo.Entidades")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Actos.SitioWeb.MVC.ServicioWeb.Victima))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Actos.SitioWeb.MVC.ServicioWeb.Agresor))]
    public partial class Persona : Actos.SitioWeb.MVC.ServicioWeb.EntidadBaseOfint {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApodoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EstaBorradoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apellido {
            get {
                return this.ApellidoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoField, value) != true)) {
                    this.ApellidoField = value;
                    this.RaisePropertyChanged("Apellido");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Apodo {
            get {
                return this.ApodoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApodoField, value) != true)) {
                    this.ApodoField = value;
                    this.RaisePropertyChanged("Apodo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool EstaBorrado {
            get {
                return this.EstaBorradoField;
            }
            set {
                if ((this.EstaBorradoField.Equals(value) != true)) {
                    this.EstaBorradoField = value;
                    this.RaisePropertyChanged("EstaBorrado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Victima", Namespace="http://schemas.datacontract.org/2004/07/Actos.Modelo.Entidades")]
    [System.SerializableAttribute()]
    public partial class Victima : Actos.SitioWeb.MVC.ServicioWeb.Persona {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaveField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Clave {
            get {
                return this.ClaveField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveField, value) != true)) {
                    this.ClaveField = value;
                    this.RaisePropertyChanged("Clave");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Agresor", Namespace="http://schemas.datacontract.org/2004/07/Actos.Modelo.Entidades")]
    [System.SerializableAttribute()]
    public partial class Agresor : Actos.SitioWeb.MVC.ServicioWeb.Persona {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CaracteristicasField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Actos.SitioWeb.MVC.ServicioWeb.Direccion[] DireccionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] FotoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MetodosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OcupacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PuntajeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Actos.SitioWeb.MVC.ServicioWeb.RedSocial[] RedesSocialesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Actos.SitioWeb.MVC.ServicioWeb.Telefono[] TelefonosField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Caracteristicas {
            get {
                return this.CaracteristicasField;
            }
            set {
                if ((object.ReferenceEquals(this.CaracteristicasField, value) != true)) {
                    this.CaracteristicasField = value;
                    this.RaisePropertyChanged("Caracteristicas");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Actos.SitioWeb.MVC.ServicioWeb.Direccion[] Direcciones {
            get {
                return this.DireccionesField;
            }
            set {
                if ((object.ReferenceEquals(this.DireccionesField, value) != true)) {
                    this.DireccionesField = value;
                    this.RaisePropertyChanged("Direcciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Foto {
            get {
                return this.FotoField;
            }
            set {
                if ((object.ReferenceEquals(this.FotoField, value) != true)) {
                    this.FotoField = value;
                    this.RaisePropertyChanged("Foto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Metodos {
            get {
                return this.MetodosField;
            }
            set {
                if ((object.ReferenceEquals(this.MetodosField, value) != true)) {
                    this.MetodosField = value;
                    this.RaisePropertyChanged("Metodos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ocupacion {
            get {
                return this.OcupacionField;
            }
            set {
                if ((object.ReferenceEquals(this.OcupacionField, value) != true)) {
                    this.OcupacionField = value;
                    this.RaisePropertyChanged("Ocupacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Puntaje {
            get {
                return this.PuntajeField;
            }
            set {
                if ((this.PuntajeField.Equals(value) != true)) {
                    this.PuntajeField = value;
                    this.RaisePropertyChanged("Puntaje");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Actos.SitioWeb.MVC.ServicioWeb.RedSocial[] RedesSociales {
            get {
                return this.RedesSocialesField;
            }
            set {
                if ((object.ReferenceEquals(this.RedesSocialesField, value) != true)) {
                    this.RedesSocialesField = value;
                    this.RaisePropertyChanged("RedesSociales");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Actos.SitioWeb.MVC.ServicioWeb.Telefono[] Telefonos {
            get {
                return this.TelefonosField;
            }
            set {
                if ((object.ReferenceEquals(this.TelefonosField, value) != true)) {
                    this.TelefonosField = value;
                    this.RaisePropertyChanged("Telefonos");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Direccion", Namespace="http://schemas.datacontract.org/2004/07/Actos.Modelo.Entidades")]
    [System.SerializableAttribute()]
    public partial class Direccion : Actos.SitioWeb.MVC.ServicioWeb.EntidadBaseOfint {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CalleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Actos.SitioWeb.MVC.ServicioWeb.Localidad LocalidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PisoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Actos.SitioWeb.MVC.ServicioWeb.TipoDireccion TipoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Calle {
            get {
                return this.CalleField;
            }
            set {
                if ((object.ReferenceEquals(this.CalleField, value) != true)) {
                    this.CalleField = value;
                    this.RaisePropertyChanged("Calle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Departamento {
            get {
                return this.DepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartamentoField, value) != true)) {
                    this.DepartamentoField = value;
                    this.RaisePropertyChanged("Departamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Actos.SitioWeb.MVC.ServicioWeb.Localidad Localidad {
            get {
                return this.LocalidadField;
            }
            set {
                if ((object.ReferenceEquals(this.LocalidadField, value) != true)) {
                    this.LocalidadField = value;
                    this.RaisePropertyChanged("Localidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroField, value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Piso {
            get {
                return this.PisoField;
            }
            set {
                if ((object.ReferenceEquals(this.PisoField, value) != true)) {
                    this.PisoField = value;
                    this.RaisePropertyChanged("Piso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Actos.SitioWeb.MVC.ServicioWeb.TipoDireccion Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RedSocial", Namespace="http://schemas.datacontract.org/2004/07/Actos.Modelo.Entidades")]
    [System.SerializableAttribute()]
    public partial class RedSocial : Actos.SitioWeb.MVC.ServicioWeb.EntidadBaseOfint {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Actos.SitioWeb.MVC.ServicioWeb.TipoRedSocial TipoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Actos.SitioWeb.MVC.ServicioWeb.TipoRedSocial Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Telefono", Namespace="http://schemas.datacontract.org/2004/07/Actos.Modelo.Entidades")]
    [System.SerializableAttribute()]
    public partial class Telefono : Actos.SitioWeb.MVC.ServicioWeb.EntidadBaseOfint {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Actos.SitioWeb.MVC.ServicioWeb.Localidad LocalidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Actos.SitioWeb.MVC.ServicioWeb.TipoTelefono TipoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Actos.SitioWeb.MVC.ServicioWeb.Localidad Localidad {
            get {
                return this.LocalidadField;
            }
            set {
                if ((object.ReferenceEquals(this.LocalidadField, value) != true)) {
                    this.LocalidadField = value;
                    this.RaisePropertyChanged("Localidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Numero {
            get {
                return this.NumeroField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroField, value) != true)) {
                    this.NumeroField = value;
                    this.RaisePropertyChanged("Numero");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Actos.SitioWeb.MVC.ServicioWeb.TipoTelefono Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Localidad", Namespace="http://schemas.datacontract.org/2004/07/Actos.Modelo.Entidades")]
    [System.SerializableAttribute()]
    public partial class Localidad : Actos.SitioWeb.MVC.ServicioWeb.EntidadBaseOfint {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoAreaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoArea {
            get {
                return this.CodigoAreaField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoAreaField, value) != true)) {
                    this.CodigoAreaField = value;
                    this.RaisePropertyChanged("CodigoArea");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Estado", Namespace="http://schemas.datacontract.org/2004/07/Actos.Modelo.Entidades.Tipos")]
    [System.SerializableAttribute()]
    public partial class Estado : Actos.SitioWeb.MVC.ServicioWeb.TipoBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoDireccion", Namespace="http://schemas.datacontract.org/2004/07/Actos.Modelo.Entidades.Tipos")]
    [System.SerializableAttribute()]
    public partial class TipoDireccion : Actos.SitioWeb.MVC.ServicioWeb.TipoBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EntidadBaseOfunsignedByte", Namespace="http://schemas.datacontract.org/2004/07/Actos.Modelo.Entidades")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Actos.SitioWeb.MVC.ServicioWeb.TipoBase))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Actos.SitioWeb.MVC.ServicioWeb.TipoRedSocial))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Actos.SitioWeb.MVC.ServicioWeb.TipoTelefono))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Actos.SitioWeb.MVC.ServicioWeb.Estado))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Actos.SitioWeb.MVC.ServicioWeb.TipoDireccion))]
    public partial class EntidadBaseOfunsignedByte : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoBase", Namespace="http://schemas.datacontract.org/2004/07/Actos.Modelo.Entidades.Tipos")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Actos.SitioWeb.MVC.ServicioWeb.TipoRedSocial))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Actos.SitioWeb.MVC.ServicioWeb.TipoTelefono))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Actos.SitioWeb.MVC.ServicioWeb.Estado))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Actos.SitioWeb.MVC.ServicioWeb.TipoDireccion))]
    public partial class TipoBase : Actos.SitioWeb.MVC.ServicioWeb.EntidadBaseOfunsignedByte {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoRedSocial", Namespace="http://schemas.datacontract.org/2004/07/Actos.Modelo.Entidades.Tipos")]
    [System.SerializableAttribute()]
    public partial class TipoRedSocial : Actos.SitioWeb.MVC.ServicioWeb.TipoBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoTelefono", Namespace="http://schemas.datacontract.org/2004/07/Actos.Modelo.Entidades.Tipos")]
    [System.SerializableAttribute()]
    public partial class TipoTelefono : Actos.SitioWeb.MVC.ServicioWeb.TipoBase {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioWeb.IServicio")]
    public interface IServicio {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/CrearLocalidad", ReplyAction="http://tempuri.org/IServicio/CrearLocalidadResponse")]
        int CrearLocalidad(Actos.SitioWeb.MVC.ServicioWeb.Localidad localidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/CrearLocalidad", ReplyAction="http://tempuri.org/IServicio/CrearLocalidadResponse")]
        System.Threading.Tasks.Task<int> CrearLocalidadAsync(Actos.SitioWeb.MVC.ServicioWeb.Localidad localidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ModificarLocalidad", ReplyAction="http://tempuri.org/IServicio/ModificarLocalidadResponse")]
        void ModificarLocalidad(Actos.SitioWeb.MVC.ServicioWeb.Localidad localidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ModificarLocalidad", ReplyAction="http://tempuri.org/IServicio/ModificarLocalidadResponse")]
        System.Threading.Tasks.Task ModificarLocalidadAsync(Actos.SitioWeb.MVC.ServicioWeb.Localidad localidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/EliminarLocalidad", ReplyAction="http://tempuri.org/IServicio/EliminarLocalidadResponse")]
        Actos.SitioWeb.MVC.ServicioWeb.Localidad EliminarLocalidad(Actos.SitioWeb.MVC.ServicioWeb.Localidad localidad, Actos.SitioWeb.MVC.ServicioWeb.Localidad localidadReemplazo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/EliminarLocalidad", ReplyAction="http://tempuri.org/IServicio/EliminarLocalidadResponse")]
        System.Threading.Tasks.Task<Actos.SitioWeb.MVC.ServicioWeb.Localidad> EliminarLocalidadAsync(Actos.SitioWeb.MVC.ServicioWeb.Localidad localidad, Actos.SitioWeb.MVC.ServicioWeb.Localidad localidadReemplazo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/DevolverLocalidadPorId", ReplyAction="http://tempuri.org/IServicio/DevolverLocalidadPorIdResponse")]
        Actos.SitioWeb.MVC.ServicioWeb.Localidad DevolverLocalidadPorId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/DevolverLocalidadPorId", ReplyAction="http://tempuri.org/IServicio/DevolverLocalidadPorIdResponse")]
        System.Threading.Tasks.Task<Actos.SitioWeb.MVC.ServicioWeb.Localidad> DevolverLocalidadPorIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/DevolverLocalidad", ReplyAction="http://tempuri.org/IServicio/DevolverLocalidadResponse")]
        Actos.SitioWeb.MVC.ServicioWeb.Localidad[] DevolverLocalidad();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/DevolverLocalidad", ReplyAction="http://tempuri.org/IServicio/DevolverLocalidadResponse")]
        System.Threading.Tasks.Task<Actos.SitioWeb.MVC.ServicioWeb.Localidad[]> DevolverLocalidadAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/CrearAntecedente", ReplyAction="http://tempuri.org/IServicio/CrearAntecedenteResponse")]
        int CrearAntecedente(Actos.SitioWeb.MVC.ServicioWeb.Antecedente antecedente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/CrearAntecedente", ReplyAction="http://tempuri.org/IServicio/CrearAntecedenteResponse")]
        System.Threading.Tasks.Task<int> CrearAntecedenteAsync(Actos.SitioWeb.MVC.ServicioWeb.Antecedente antecedente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ModificarAntecedente", ReplyAction="http://tempuri.org/IServicio/ModificarAntecedenteResponse")]
        void ModificarAntecedente(Actos.SitioWeb.MVC.ServicioWeb.Antecedente antecedente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ModificarAntecedente", ReplyAction="http://tempuri.org/IServicio/ModificarAntecedenteResponse")]
        System.Threading.Tasks.Task ModificarAntecedenteAsync(Actos.SitioWeb.MVC.ServicioWeb.Antecedente antecedente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/EliminarAntecedente", ReplyAction="http://tempuri.org/IServicio/EliminarAntecedenteResponse")]
        void EliminarAntecedente(Actos.SitioWeb.MVC.ServicioWeb.Antecedente antecedente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/EliminarAntecedente", ReplyAction="http://tempuri.org/IServicio/EliminarAntecedenteResponse")]
        System.Threading.Tasks.Task EliminarAntecedenteAsync(Actos.SitioWeb.MVC.ServicioWeb.Antecedente antecedente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/DevolverAntecedentePorId", ReplyAction="http://tempuri.org/IServicio/DevolverAntecedentePorIdResponse")]
        Actos.SitioWeb.MVC.ServicioWeb.Antecedente DevolverAntecedentePorId(int id, bool puntajes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/DevolverAntecedentePorId", ReplyAction="http://tempuri.org/IServicio/DevolverAntecedentePorIdResponse")]
        System.Threading.Tasks.Task<Actos.SitioWeb.MVC.ServicioWeb.Antecedente> DevolverAntecedentePorIdAsync(int id, bool puntajes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/DevolverAntecedentesPorAgresor", ReplyAction="http://tempuri.org/IServicio/DevolverAntecedentesPorAgresorResponse")]
        Actos.SitioWeb.MVC.ServicioWeb.Antecedente[] DevolverAntecedentesPorAgresor(Actos.SitioWeb.MVC.ServicioWeb.Agresor agresor, bool puntajes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/DevolverAntecedentesPorAgresor", ReplyAction="http://tempuri.org/IServicio/DevolverAntecedentesPorAgresorResponse")]
        System.Threading.Tasks.Task<Actos.SitioWeb.MVC.ServicioWeb.Antecedente[]> DevolverAntecedentesPorAgresorAsync(Actos.SitioWeb.MVC.ServicioWeb.Agresor agresor, bool puntajes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/DevolverAntecedentesPorVictima", ReplyAction="http://tempuri.org/IServicio/DevolverAntecedentesPorVictimaResponse")]
        Actos.SitioWeb.MVC.ServicioWeb.Antecedente[] DevolverAntecedentesPorVictima(Actos.SitioWeb.MVC.ServicioWeb.Victima victima, bool puntajes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/DevolverAntecedentesPorVictima", ReplyAction="http://tempuri.org/IServicio/DevolverAntecedentesPorVictimaResponse")]
        System.Threading.Tasks.Task<Actos.SitioWeb.MVC.ServicioWeb.Antecedente[]> DevolverAntecedentesPorVictimaAsync(Actos.SitioWeb.MVC.ServicioWeb.Victima victima, bool puntajes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/DevolverAntecedentes", ReplyAction="http://tempuri.org/IServicio/DevolverAntecedentesResponse")]
        Actos.SitioWeb.MVC.ServicioWeb.Antecedente[] DevolverAntecedentes(bool puntajes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/DevolverAntecedentes", ReplyAction="http://tempuri.org/IServicio/DevolverAntecedentesResponse")]
        System.Threading.Tasks.Task<Actos.SitioWeb.MVC.ServicioWeb.Antecedente[]> DevolverAntecedentesAsync(bool puntajes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/AgregarPuntaje", ReplyAction="http://tempuri.org/IServicio/AgregarPuntajeResponse")]
        void AgregarPuntaje(Actos.SitioWeb.MVC.ServicioWeb.Antecedente antecedente, Actos.SitioWeb.MVC.ServicioWeb.Victima victima);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/AgregarPuntaje", ReplyAction="http://tempuri.org/IServicio/AgregarPuntajeResponse")]
        System.Threading.Tasks.Task AgregarPuntajeAsync(Actos.SitioWeb.MVC.ServicioWeb.Antecedente antecedente, Actos.SitioWeb.MVC.ServicioWeb.Victima victima);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/DevolverEstados", ReplyAction="http://tempuri.org/IServicio/DevolverEstadosResponse")]
        Actos.SitioWeb.MVC.ServicioWeb.Estado[] DevolverEstados();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/DevolverEstados", ReplyAction="http://tempuri.org/IServicio/DevolverEstadosResponse")]
        System.Threading.Tasks.Task<Actos.SitioWeb.MVC.ServicioWeb.Estado[]> DevolverEstadosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/DevolverTiposDirecciones", ReplyAction="http://tempuri.org/IServicio/DevolverTiposDireccionesResponse")]
        Actos.SitioWeb.MVC.ServicioWeb.TipoDireccion[] DevolverTiposDirecciones();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/DevolverTiposDirecciones", ReplyAction="http://tempuri.org/IServicio/DevolverTiposDireccionesResponse")]
        System.Threading.Tasks.Task<Actos.SitioWeb.MVC.ServicioWeb.TipoDireccion[]> DevolverTiposDireccionesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/DevolverTiposRedesSociales", ReplyAction="http://tempuri.org/IServicio/DevolverTiposRedesSocialesResponse")]
        Actos.SitioWeb.MVC.ServicioWeb.TipoRedSocial[] DevolverTiposRedesSociales();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/DevolverTiposRedesSociales", ReplyAction="http://tempuri.org/IServicio/DevolverTiposRedesSocialesResponse")]
        System.Threading.Tasks.Task<Actos.SitioWeb.MVC.ServicioWeb.TipoRedSocial[]> DevolverTiposRedesSocialesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/DevolverTiposTelefonos", ReplyAction="http://tempuri.org/IServicio/DevolverTiposTelefonosResponse")]
        Actos.SitioWeb.MVC.ServicioWeb.TipoTelefono[] DevolverTiposTelefonos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/DevolverTiposTelefonos", ReplyAction="http://tempuri.org/IServicio/DevolverTiposTelefonosResponse")]
        System.Threading.Tasks.Task<Actos.SitioWeb.MVC.ServicioWeb.TipoTelefono[]> DevolverTiposTelefonosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/CrearAgresor", ReplyAction="http://tempuri.org/IServicio/CrearAgresorResponse")]
        int CrearAgresor(Actos.SitioWeb.MVC.ServicioWeb.Agresor agresor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/CrearAgresor", ReplyAction="http://tempuri.org/IServicio/CrearAgresorResponse")]
        System.Threading.Tasks.Task<int> CrearAgresorAsync(Actos.SitioWeb.MVC.ServicioWeb.Agresor agresor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ModificarAgresor", ReplyAction="http://tempuri.org/IServicio/ModificarAgresorResponse")]
        void ModificarAgresor(Actos.SitioWeb.MVC.ServicioWeb.Agresor agresor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ModificarAgresor", ReplyAction="http://tempuri.org/IServicio/ModificarAgresorResponse")]
        System.Threading.Tasks.Task ModificarAgresorAsync(Actos.SitioWeb.MVC.ServicioWeb.Agresor agresor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/EliminarAgresor", ReplyAction="http://tempuri.org/IServicio/EliminarAgresorResponse")]
        void EliminarAgresor(Actos.SitioWeb.MVC.ServicioWeb.Agresor agresor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/EliminarAgresor", ReplyAction="http://tempuri.org/IServicio/EliminarAgresorResponse")]
        System.Threading.Tasks.Task EliminarAgresorAsync(Actos.SitioWeb.MVC.ServicioWeb.Agresor agresor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/DevolverAgresorPorId", ReplyAction="http://tempuri.org/IServicio/DevolverAgresorPorIdResponse")]
        Actos.SitioWeb.MVC.ServicioWeb.Agresor DevolverAgresorPorId(int id, bool telefonos, bool direcciones, bool redesSociales);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/DevolverAgresorPorId", ReplyAction="http://tempuri.org/IServicio/DevolverAgresorPorIdResponse")]
        System.Threading.Tasks.Task<Actos.SitioWeb.MVC.ServicioWeb.Agresor> DevolverAgresorPorIdAsync(int id, bool telefonos, bool direcciones, bool redesSociales);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/DevolverAgresores", ReplyAction="http://tempuri.org/IServicio/DevolverAgresoresResponse")]
        Actos.SitioWeb.MVC.ServicioWeb.Agresor[] DevolverAgresores(bool telefonos, bool direcciones, bool redesSociales);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/DevolverAgresores", ReplyAction="http://tempuri.org/IServicio/DevolverAgresoresResponse")]
        System.Threading.Tasks.Task<Actos.SitioWeb.MVC.ServicioWeb.Agresor[]> DevolverAgresoresAsync(bool telefonos, bool direcciones, bool redesSociales);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/CrearVictima", ReplyAction="http://tempuri.org/IServicio/CrearVictimaResponse")]
        int CrearVictima(Actos.SitioWeb.MVC.ServicioWeb.Victima victima);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/CrearVictima", ReplyAction="http://tempuri.org/IServicio/CrearVictimaResponse")]
        System.Threading.Tasks.Task<int> CrearVictimaAsync(Actos.SitioWeb.MVC.ServicioWeb.Victima victima);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ModificarVictima", ReplyAction="http://tempuri.org/IServicio/ModificarVictimaResponse")]
        void ModificarVictima(Actos.SitioWeb.MVC.ServicioWeb.Victima victima);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ModificarVictima", ReplyAction="http://tempuri.org/IServicio/ModificarVictimaResponse")]
        System.Threading.Tasks.Task ModificarVictimaAsync(Actos.SitioWeb.MVC.ServicioWeb.Victima victima);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/EliminarVictima", ReplyAction="http://tempuri.org/IServicio/EliminarVictimaResponse")]
        void EliminarVictima(Actos.SitioWeb.MVC.ServicioWeb.Victima victima);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/EliminarVictima", ReplyAction="http://tempuri.org/IServicio/EliminarVictimaResponse")]
        System.Threading.Tasks.Task EliminarVictimaAsync(Actos.SitioWeb.MVC.ServicioWeb.Victima victima);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/DevolverVictimaPorId", ReplyAction="http://tempuri.org/IServicio/DevolverVictimaPorIdResponse")]
        Actos.SitioWeb.MVC.ServicioWeb.Victima DevolverVictimaPorId(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/DevolverVictimaPorId", ReplyAction="http://tempuri.org/IServicio/DevolverVictimaPorIdResponse")]
        System.Threading.Tasks.Task<Actos.SitioWeb.MVC.ServicioWeb.Victima> DevolverVictimaPorIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/DevolverVictimas", ReplyAction="http://tempuri.org/IServicio/DevolverVictimasResponse")]
        Actos.SitioWeb.MVC.ServicioWeb.Victima[] DevolverVictimas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/DevolverVictimas", ReplyAction="http://tempuri.org/IServicio/DevolverVictimasResponse")]
        System.Threading.Tasks.Task<Actos.SitioWeb.MVC.ServicioWeb.Victima[]> DevolverVictimasAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioChannel : Actos.SitioWeb.MVC.ServicioWeb.IServicio, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioClient : System.ServiceModel.ClientBase<Actos.SitioWeb.MVC.ServicioWeb.IServicio>, Actos.SitioWeb.MVC.ServicioWeb.IServicio {
        
        public ServicioClient() {
        }
        
        public ServicioClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CrearLocalidad(Actos.SitioWeb.MVC.ServicioWeb.Localidad localidad) {
            return base.Channel.CrearLocalidad(localidad);
        }
        
        public System.Threading.Tasks.Task<int> CrearLocalidadAsync(Actos.SitioWeb.MVC.ServicioWeb.Localidad localidad) {
            return base.Channel.CrearLocalidadAsync(localidad);
        }
        
        public void ModificarLocalidad(Actos.SitioWeb.MVC.ServicioWeb.Localidad localidad) {
            base.Channel.ModificarLocalidad(localidad);
        }
        
        public System.Threading.Tasks.Task ModificarLocalidadAsync(Actos.SitioWeb.MVC.ServicioWeb.Localidad localidad) {
            return base.Channel.ModificarLocalidadAsync(localidad);
        }
        
        public Actos.SitioWeb.MVC.ServicioWeb.Localidad EliminarLocalidad(Actos.SitioWeb.MVC.ServicioWeb.Localidad localidad, Actos.SitioWeb.MVC.ServicioWeb.Localidad localidadReemplazo) {
            return base.Channel.EliminarLocalidad(localidad, localidadReemplazo);
        }
        
        public System.Threading.Tasks.Task<Actos.SitioWeb.MVC.ServicioWeb.Localidad> EliminarLocalidadAsync(Actos.SitioWeb.MVC.ServicioWeb.Localidad localidad, Actos.SitioWeb.MVC.ServicioWeb.Localidad localidadReemplazo) {
            return base.Channel.EliminarLocalidadAsync(localidad, localidadReemplazo);
        }
        
        public Actos.SitioWeb.MVC.ServicioWeb.Localidad DevolverLocalidadPorId(int id) {
            return base.Channel.DevolverLocalidadPorId(id);
        }
        
        public System.Threading.Tasks.Task<Actos.SitioWeb.MVC.ServicioWeb.Localidad> DevolverLocalidadPorIdAsync(int id) {
            return base.Channel.DevolverLocalidadPorIdAsync(id);
        }
        
        public Actos.SitioWeb.MVC.ServicioWeb.Localidad[] DevolverLocalidad() {
            return base.Channel.DevolverLocalidad();
        }
        
        public System.Threading.Tasks.Task<Actos.SitioWeb.MVC.ServicioWeb.Localidad[]> DevolverLocalidadAsync() {
            return base.Channel.DevolverLocalidadAsync();
        }
        
        public int CrearAntecedente(Actos.SitioWeb.MVC.ServicioWeb.Antecedente antecedente) {
            return base.Channel.CrearAntecedente(antecedente);
        }
        
        public System.Threading.Tasks.Task<int> CrearAntecedenteAsync(Actos.SitioWeb.MVC.ServicioWeb.Antecedente antecedente) {
            return base.Channel.CrearAntecedenteAsync(antecedente);
        }
        
        public void ModificarAntecedente(Actos.SitioWeb.MVC.ServicioWeb.Antecedente antecedente) {
            base.Channel.ModificarAntecedente(antecedente);
        }
        
        public System.Threading.Tasks.Task ModificarAntecedenteAsync(Actos.SitioWeb.MVC.ServicioWeb.Antecedente antecedente) {
            return base.Channel.ModificarAntecedenteAsync(antecedente);
        }
        
        public void EliminarAntecedente(Actos.SitioWeb.MVC.ServicioWeb.Antecedente antecedente) {
            base.Channel.EliminarAntecedente(antecedente);
        }
        
        public System.Threading.Tasks.Task EliminarAntecedenteAsync(Actos.SitioWeb.MVC.ServicioWeb.Antecedente antecedente) {
            return base.Channel.EliminarAntecedenteAsync(antecedente);
        }
        
        public Actos.SitioWeb.MVC.ServicioWeb.Antecedente DevolverAntecedentePorId(int id, bool puntajes) {
            return base.Channel.DevolverAntecedentePorId(id, puntajes);
        }
        
        public System.Threading.Tasks.Task<Actos.SitioWeb.MVC.ServicioWeb.Antecedente> DevolverAntecedentePorIdAsync(int id, bool puntajes) {
            return base.Channel.DevolverAntecedentePorIdAsync(id, puntajes);
        }
        
        public Actos.SitioWeb.MVC.ServicioWeb.Antecedente[] DevolverAntecedentesPorAgresor(Actos.SitioWeb.MVC.ServicioWeb.Agresor agresor, bool puntajes) {
            return base.Channel.DevolverAntecedentesPorAgresor(agresor, puntajes);
        }
        
        public System.Threading.Tasks.Task<Actos.SitioWeb.MVC.ServicioWeb.Antecedente[]> DevolverAntecedentesPorAgresorAsync(Actos.SitioWeb.MVC.ServicioWeb.Agresor agresor, bool puntajes) {
            return base.Channel.DevolverAntecedentesPorAgresorAsync(agresor, puntajes);
        }
        
        public Actos.SitioWeb.MVC.ServicioWeb.Antecedente[] DevolverAntecedentesPorVictima(Actos.SitioWeb.MVC.ServicioWeb.Victima victima, bool puntajes) {
            return base.Channel.DevolverAntecedentesPorVictima(victima, puntajes);
        }
        
        public System.Threading.Tasks.Task<Actos.SitioWeb.MVC.ServicioWeb.Antecedente[]> DevolverAntecedentesPorVictimaAsync(Actos.SitioWeb.MVC.ServicioWeb.Victima victima, bool puntajes) {
            return base.Channel.DevolverAntecedentesPorVictimaAsync(victima, puntajes);
        }
        
        public Actos.SitioWeb.MVC.ServicioWeb.Antecedente[] DevolverAntecedentes(bool puntajes) {
            return base.Channel.DevolverAntecedentes(puntajes);
        }
        
        public System.Threading.Tasks.Task<Actos.SitioWeb.MVC.ServicioWeb.Antecedente[]> DevolverAntecedentesAsync(bool puntajes) {
            return base.Channel.DevolverAntecedentesAsync(puntajes);
        }
        
        public void AgregarPuntaje(Actos.SitioWeb.MVC.ServicioWeb.Antecedente antecedente, Actos.SitioWeb.MVC.ServicioWeb.Victima victima) {
            base.Channel.AgregarPuntaje(antecedente, victima);
        }
        
        public System.Threading.Tasks.Task AgregarPuntajeAsync(Actos.SitioWeb.MVC.ServicioWeb.Antecedente antecedente, Actos.SitioWeb.MVC.ServicioWeb.Victima victima) {
            return base.Channel.AgregarPuntajeAsync(antecedente, victima);
        }
        
        public Actos.SitioWeb.MVC.ServicioWeb.Estado[] DevolverEstados() {
            return base.Channel.DevolverEstados();
        }
        
        public System.Threading.Tasks.Task<Actos.SitioWeb.MVC.ServicioWeb.Estado[]> DevolverEstadosAsync() {
            return base.Channel.DevolverEstadosAsync();
        }
        
        public Actos.SitioWeb.MVC.ServicioWeb.TipoDireccion[] DevolverTiposDirecciones() {
            return base.Channel.DevolverTiposDirecciones();
        }
        
        public System.Threading.Tasks.Task<Actos.SitioWeb.MVC.ServicioWeb.TipoDireccion[]> DevolverTiposDireccionesAsync() {
            return base.Channel.DevolverTiposDireccionesAsync();
        }
        
        public Actos.SitioWeb.MVC.ServicioWeb.TipoRedSocial[] DevolverTiposRedesSociales() {
            return base.Channel.DevolverTiposRedesSociales();
        }
        
        public System.Threading.Tasks.Task<Actos.SitioWeb.MVC.ServicioWeb.TipoRedSocial[]> DevolverTiposRedesSocialesAsync() {
            return base.Channel.DevolverTiposRedesSocialesAsync();
        }
        
        public Actos.SitioWeb.MVC.ServicioWeb.TipoTelefono[] DevolverTiposTelefonos() {
            return base.Channel.DevolverTiposTelefonos();
        }
        
        public System.Threading.Tasks.Task<Actos.SitioWeb.MVC.ServicioWeb.TipoTelefono[]> DevolverTiposTelefonosAsync() {
            return base.Channel.DevolverTiposTelefonosAsync();
        }
        
        public int CrearAgresor(Actos.SitioWeb.MVC.ServicioWeb.Agresor agresor) {
            return base.Channel.CrearAgresor(agresor);
        }
        
        public System.Threading.Tasks.Task<int> CrearAgresorAsync(Actos.SitioWeb.MVC.ServicioWeb.Agresor agresor) {
            return base.Channel.CrearAgresorAsync(agresor);
        }
        
        public void ModificarAgresor(Actos.SitioWeb.MVC.ServicioWeb.Agresor agresor) {
            base.Channel.ModificarAgresor(agresor);
        }
        
        public System.Threading.Tasks.Task ModificarAgresorAsync(Actos.SitioWeb.MVC.ServicioWeb.Agresor agresor) {
            return base.Channel.ModificarAgresorAsync(agresor);
        }
        
        public void EliminarAgresor(Actos.SitioWeb.MVC.ServicioWeb.Agresor agresor) {
            base.Channel.EliminarAgresor(agresor);
        }
        
        public System.Threading.Tasks.Task EliminarAgresorAsync(Actos.SitioWeb.MVC.ServicioWeb.Agresor agresor) {
            return base.Channel.EliminarAgresorAsync(agresor);
        }
        
        public Actos.SitioWeb.MVC.ServicioWeb.Agresor DevolverAgresorPorId(int id, bool telefonos, bool direcciones, bool redesSociales) {
            return base.Channel.DevolverAgresorPorId(id, telefonos, direcciones, redesSociales);
        }
        
        public System.Threading.Tasks.Task<Actos.SitioWeb.MVC.ServicioWeb.Agresor> DevolverAgresorPorIdAsync(int id, bool telefonos, bool direcciones, bool redesSociales) {
            return base.Channel.DevolverAgresorPorIdAsync(id, telefonos, direcciones, redesSociales);
        }
        
        public Actos.SitioWeb.MVC.ServicioWeb.Agresor[] DevolverAgresores(bool telefonos, bool direcciones, bool redesSociales) {
            return base.Channel.DevolverAgresores(telefonos, direcciones, redesSociales);
        }
        
        public System.Threading.Tasks.Task<Actos.SitioWeb.MVC.ServicioWeb.Agresor[]> DevolverAgresoresAsync(bool telefonos, bool direcciones, bool redesSociales) {
            return base.Channel.DevolverAgresoresAsync(telefonos, direcciones, redesSociales);
        }
        
        public int CrearVictima(Actos.SitioWeb.MVC.ServicioWeb.Victima victima) {
            return base.Channel.CrearVictima(victima);
        }
        
        public System.Threading.Tasks.Task<int> CrearVictimaAsync(Actos.SitioWeb.MVC.ServicioWeb.Victima victima) {
            return base.Channel.CrearVictimaAsync(victima);
        }
        
        public void ModificarVictima(Actos.SitioWeb.MVC.ServicioWeb.Victima victima) {
            base.Channel.ModificarVictima(victima);
        }
        
        public System.Threading.Tasks.Task ModificarVictimaAsync(Actos.SitioWeb.MVC.ServicioWeb.Victima victima) {
            return base.Channel.ModificarVictimaAsync(victima);
        }
        
        public void EliminarVictima(Actos.SitioWeb.MVC.ServicioWeb.Victima victima) {
            base.Channel.EliminarVictima(victima);
        }
        
        public System.Threading.Tasks.Task EliminarVictimaAsync(Actos.SitioWeb.MVC.ServicioWeb.Victima victima) {
            return base.Channel.EliminarVictimaAsync(victima);
        }
        
        public Actos.SitioWeb.MVC.ServicioWeb.Victima DevolverVictimaPorId(int id) {
            return base.Channel.DevolverVictimaPorId(id);
        }
        
        public System.Threading.Tasks.Task<Actos.SitioWeb.MVC.ServicioWeb.Victima> DevolverVictimaPorIdAsync(int id) {
            return base.Channel.DevolverVictimaPorIdAsync(id);
        }
        
        public Actos.SitioWeb.MVC.ServicioWeb.Victima[] DevolverVictimas() {
            return base.Channel.DevolverVictimas();
        }
        
        public System.Threading.Tasks.Task<Actos.SitioWeb.MVC.ServicioWeb.Victima[]> DevolverVictimasAsync() {
            return base.Channel.DevolverVictimasAsync();
        }
    }
}
